"""init migrations

Revision ID: ecc2b64f7749
Revises: 
Create Date: 2023-09-26 15:20:30.927423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc2b64f7749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('variant_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_3', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
